In [5]:
import numpy as np 
np.empty((4,4), dtype = int)

array([[                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
        -9223366536023648123],
       [                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
                           0]])

In [3]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
a = np.arange(1,20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [8]:
a = np.arange(2, 20, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [12]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
a = a.flatten()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])